export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const CREATE_PHOTO_SUCCESS="CREATE_PHOTO_SUCCESS";
export const DELETE_PHOTO_SUCCESS="DELETE_PHOTO_SUCCESS";

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_CURRENT_AUTHOR_PHOTOS_SUCCESS = "FETCH_CURRENT_AUTHOR_PHOTOS_SUCCESS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_CURRENT_AUTHOR_SUCCESS="FETCH_CURRENT_AUTHOR_SUCCESS";

